### ISSUE TITLE
Uglify removes function names by default, breaks on stateless components

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/react-redux-component-init#13]
If stateless components don't have a `name` anymore, it will break on [this line](https://github.com/mediamonks/react-redux-component-init/blob/95fd028c61d5234267afd29bb706756268b0955b/src/withInitAction.js#L80).

The check `const componentId = WrappedComponent.displayName || WrappedComponent.name;` will return an empty string.

`react-redux` falls back on `"Component"` when there is no name:
```
    const wrappedComponentName = WrappedComponent.displayName
      || WrappedComponent.name
      || 'Component'
```

However, not sure if that is what we want, since that will throw similar errors as we now have with ReduxForm:
`Each Component passed to withInitAction() should have a unique displayName. Found duplicate name "Connect(ReduxForm)"`

The only thing I can think of is that we force people to use the `keep_fnames` flag in Uglify.

Or maybe to use [babel-plugin-transform-react-stateless-component-name](https://github.com/wyze/babel-plugin-transform-react-stateless-component-name) to add a `displayName` property that will not be removed by Uglify?

Still, both options need custom config from users to make this module work.

**Comment by flut1** [comment]
We need an identifier that is both unique for every component but the same for different builds (web and node). I'm starting to doubt if displayName is really the way to go. It will already require patching of redux-form and possibly other libraries that mutate the displayName. And now on top of that uglify will need to be configured a specific way.

Maybe we need to step back to plan A, which is explicitly defining a unique identifier when calling the HoC. We will then leave it to the user what id they want to go for (for example, if you are using Webpack you might just use `module.id`)

**Comment by ThaNarie** [comment]
Adds some additional config, but probably the best option, and less error-prone. That would solve #12 as well.

**Comment by flut1** [comment]
How about an extra **optional** argument to the function that `withInitAction` returns?

```javascript
// string argument
export default withInitAction(
   [ ...props ],
   initFunction
)(MyComponent, 'MyComponent');

// function argument
export default withInitAction(
   [ ...props ],
   initFunction
)(MyComponent, Component => `myCustomPrefix${Component.displayName}`);

// default:  Component => Component.displayName;
export default withInitAction(
   [ ...props ],
   initFunction
)(MyComponent);
```

**Comment by ThaNarie** [comment]
How does that work together with `compose` ?

```
export default compose(
  addInitAction,
  connected,
  enhanced,
)(MyComponent, 'MyComponent');
```
If that even works, it seems pretty disconnected from our HoC, and not sure how other HoC's react on that if it passes it forward?

**Comment by flut1** [comment]
I haven't thought about that. How about we curry the argument? 

```
export default withInitAction(
   [ ...props ],
   initFunction
)('MyComponent')(MyComponent);
```

This would only allow for a string argument, as we cannot distinguish between a function argument and a react component. I don't think that's such a huge problem though. So that would compose with:

```
const addInitAction = withInitAction( ... );
export default compose(
  addInitAction('MyComponent'),
  connected,
  enhanced,
)(MyComponent);

// or

const addInitAction = withInitAction( ... )('MyComponent');
export default compose(
  addInitAction,
  connected,
  enhanced,
)(MyComponent);
```

**Comment by ThaNarie** [comment]
Why not pass it as a parameter/option to the HoC itself?
Or does that make it too tightly coupled? (i.e. less 'functional', can't re-use the HoC for other components anymore)

I guess your last proposal is the best of both worlds?

Additionally, we could support 'myCustomPrefix${name}' as a string where we replace the componentName internally? (as a replacement of the function)

**Comment by flut1** [comment]
> Or does that make it too tightly coupled?

I don't think this is too much of a problem practically, but it kind of defeats the purpose of having a HoC at all right? We then might as well `withInitAction(MyComponent, ...)`

> Additionally, we could support 'myCustomPrefix${name}' as a string

makes sense
