### ISSUE TITLE
Add 'flexible' option to allow components to initialize both lazy and non-lazy

### ISSUE THREAD

**Issue by flut1** [mediamonks/react-redux-component-init#14]
Sometimes we want to allow components to be prepared on the server, but self-initialize when this has not been done. This would allow for a 'flexible' component that can be a child of both a lazy and a non-lazy component. 

This configuration would be more error-prone as there is no verification that the component has been prepared as we do not know when this is desired. For that reason it should be opt-in.

**Possible naming:**
 - Is `'flexible'` a good name for this behavior? 
 - We can remove the `lazy` flag and replace it with an option that can read either `NON_LAZY` (default), `LAZY` or `FLEXIBLE`. This would be a breaking change
 - We can add an additional `flexible` flag. This feels a bit awkward as it is not clearly defined how this interacts with setting the `lazy` flag

Any other ideas?

**Comment by ThaNarie** [comment]
* don't know a better name at this time, so keep it `'flexible'`
* adding enums makes it more complicated to use, having two bools where one will be ignored should be fine

So when using this, if a parent is marked as lazy, all childs should be marked as either lazy or flexible. Leaving it default will keep throwing errors like it does now.

**Comment by flut1** [comment]
Closing this issue in favor of modifying the existing `lazy` option. See #15
