### ISSUE TITLE
Unneeded renders in `withInitAction` when `INIT_COMPONENT` fires

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/react-redux-component-init#24]
It looks like every `INIT_COMPONENT` causes all `withInitAction`'s `connect` to execute and cause re-renders.

I'm not 100% sure, but it looks like the following is happening:

1. When `INIT_COMPONENT` fires from any component, the `selfInit` in the reducer is updated where `completed` is updated for the `prepareHash` for that component:
https://github.com/mediamonks/react-redux-component-init/blob/e9341fd7486de96526075900dc5f3803daba5fdd/src/reducer.js#L36-L39

2. When that happens, the 2nd param in the selector will 'break' the memoization:
https://github.com/mediamonks/react-redux-component-init/blob/e9341fd7486de96526075900dc5f3803daba5fdd/src/reducer.js#L57

3. This will cause the `connect` in `withInitAction` to return a new object for `__componentInitState`:
https://github.com/mediamonks/react-redux-component-init/blob/e9341fd7486de96526075900dc5f3803daba5fdd/src/withInitAction.js#L200-L205

4. Because of 3), the withInitAction component will cause a re-render itself.

5. Most of the time when `withInitAction` is used to get some data, the same component is also wrapped into a `connect` to get the info from the state. The connect will not 'block' the re-render of the wrapped component, since it will only do purity checks on the output of it's own mapStateToProps.

6. And because of 4) The wrapped component will also be re-rendered. In this case, making it a `PureComponent` will halt the re-render, because the render in 4) didn't pass any new/updated props.

**Possible fix;**
1. improve the selector from 2) to better deal with state updates that are not relevant for that component, or
1. add a custom equality check for the withInitAction connect to battle the failing selector, or
2. implement a shouldComponentUpdate in the withInitAction component as a last resort.

**Example:**
If we have a tree of 50 components that have a withInitAction, and all of them will start and complete (two actions per component), all 50 components will re-render on all of the 100 actions, causing a lot of usless code execution.

**Comment by flut1** [comment]
Thanks for the thorough investigation :+1:  We should definitely fix the selector memoization, because that's the whole point of using a selector.
